Update msbuild.yml

diff --git a/.github/workflows/msbuild.yml b/.github/workflows/msbuild.yml
--- a/.github/workflows/msbuild.yml
+++ b/.github/workflows/msbuild.yml
@@ -1,6 +1,10 @@
-name: MSBuild
+name: MSBuild Windows
 
-on: [push]
+on:
+  push:
+    branches: [ master ]
+  pull_request:
+    branches: [ master ]
 
 env:
   # Path to the solution file relative to the root of the project.
@@ -13,7 +17,7 @@ env:
 
 jobs:
   build:
-    runs-on: windows-latest
+    runs-on: [ windows-latest, ubuntu-latest ]
 
     steps:
     - uses: actions/checkout@v2
@@ -30,3 +34,35 @@ jobs:
       # Add additional options to the MSBuild command line here (like platform or verbosity level).
       # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
       run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
+
+  test:
+    needs: build
+    runs-on: windows-latest
+
+    # the build-and-test job might be skipped, we don't need to run this job then
+    #if: success() || failure()
+
+    steps:
+      - name: Install NUnit.ConsoleRunner
+        run: nuget install NUnit.ConsoleRunner -Version 3.12.0
+
+      - name: Run tests
+        run: mono ./NUnit.ConsoleRunner.3.12.0/tools/nunit3-console.exe ./CompuMaster.Test.Calendar/bin/CompuMaster.Test.Calendar.dll --result=TestResult.xml
+
+      - name: Publish Unit Test Results
+        uses: EnricoMi/publish-unit-test-result-action@v1
+        if: always()
+        with:
+          files: TestResult.xml
+
+#      - name: Upload Unit Test Results
+#        if: always()
+#        uses: actions/upload-artifact@v2
+#        with:
+#          name: Unit Test Results (Python ${{ matrix.python-version }})
+#          path: pytest.xml
+#
+#      - name: Download Artifacts
+#        uses: actions/download-artifact@v2
+#        with:
+#          path: artifacts
